modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="cravings_mod"
version="0.4.0"
displayName="Cravings"
updateJSONURL="https://pastebin.com/raw/8dqiTUxX"
displayURL="https://modrinth.com/mod/cravings"
logoFile="logo.png"
credits="Developed by UniPM & p1ague_d0c"
authors="UniPM"
description="A mod for all your food needs!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.cravings_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cravings_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration